baseurl      = "https://www.edbrown.dev"
title        = "My Blog"
languageCode = "en-gb"
theme        = "hello-friend"
paginate     = 10
googleAnalytics = "G-CTCE1QT00P"

[params]
  showReadingTime = false
  contentTypeName = "posts"
  defaultTheme = "light"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Ed Brown"
    keywords = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "edbrown.dev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"